---
- hosts: nginx
  roles:
  - nginx

- hosts: mesos-master
  sudo: yes
  roles:
  - mesos-master
  
- hosts: mesos-slave
  sudo: yes
  roles:
  - mesos-slave

- hosts: nginx
  roles:
  - nginx-sites