---
- hosts: all
  sudo: yes
  roles:
  - { role: nginx, when: '"nginx" in group_names' }
  - { role: mesos-master, when: '"mesos-master" in group_names' }
  - { role: mesos-slave, when: '"mesos-slave" in group_names' }
  - { role: nginx-sites, when: '"nginx" in group_names' }
